### ISSUE TITLE
update docs to reflect new long-string reindent feature

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet-lang.org#101]
See change in 1.13.1 re backtick-delimited strings. Possible places to update:

  * [syntax page](https://janet-lang.org/docs/syntax.html) --> long strings section
  * [strings, keywords, & symbols page](https://janet-lang.org/docs/strings.html)

While we're at it, it may make sense to change the text "long strings" to "long-strings" or "longstrings" uniformly throughout, to distinguish them from other strings that just happen to be long.

Possibly related to this: PR #99 .

**Comment by sogaiu** [comment]
Please don't choose "longstrings", i.e. please do not run the words together with nothing in between.

@GrayJack and I have already been putting something between the two words in our tree-sitter grammars:

* https://github.com/GrayJack/tree-sitter-janet/blob/39422ae34badf1e6fa0ac1f748cc47ca214f6314/grammar.js#L4
* https://github.com/sogaiu/tree-sitter-janet-simple/blob/45418f750c44f409c698733e4b9276eeac91eaaa/grammar.js#L36

**Comment by uvtc** [comment]
I also think "long-string" is better (and "re-indent" over "reindent", where the latter sounds like it has something to do with reindeer :) ).

**Comment by uvtc** [comment]
Come to think of it, the long-strings feature doesn't ever indent (or re-indent) anything, does it? It always *un-indents* --- removing indentation. Maybe that term would fit better for describing long-string behaviour.

**Comment by pepe** [comment]
I think it unindents only in the docstring.

**Comment by bakpakin** [comment]
Long-string sounds good to me. The basic way the indentation works is to try and remove leading indentation, _only_ if nothing is indented left of the opening delimiter.

**Comment by sogaiu** [comment]
IIUC, some relevant code for this feature is here: https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/src/core/parse.c#L323-L367

**Comment by uvtc** [comment]
Since the newish Documentation page already addresses re/de/un-indenting of long-strings when used as docstrings, I think that the commits in #154 should wrap this up so this issue can be closed.

**Comment by sogaiu** [comment]
@uvtc IIUC you have the power to close this issue :)

**Comment by uvtc** [comment]
Gotcha. Thanks, @sogaiu .
