### ISSUE TITLE
small code example on homepage

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet-lang.org#107]
Would be nice to have a small syntax-highlighted code example somewhere on the Janet homepage.

Maybe as part of the intro paragraph at the top, after the first sentence (to the right of the logo)?

**Comment by uvtc** [comment]
I really like how this looks on the homepage! Thanks!

(Note, an abbreviation for "solutions" that I've seen and used is "solns". I thought I'd mention it because you used those other short names `tab` and `len` in the example.)

It took me a little time to reason out how that algorithm works (after looking up what the 3sum problem is), which was instructive to me.

I see you have in there `(put solutions {i true j true k true} true)` using `solutions` as a kind of "set of sets". This reminded me that it would be handy to have a native "set" type in Janet, though I see [it's been suggested before](https://github.com/janet-lang/janet/issues/59).

**Comment by uvtc** [comment]
Yes, thanks, @sogaiu . I still don't know the etiquette of who closes issues. :) Nice to have a code sample there. Closing this, and thanks for the reminder.

**Comment by sogaiu** [comment]
@uvtc I haven't seen an official statement regarding who ought to close an issue, but for reference (and in support of your closing this one), I have seen other folks close issues they have opened (I've done this too).
