### ISSUE TITLE
#comment: parse error / unmatched delimiter

### ISSUE THREAD

**Issue by jkleiser** [janet-lang/janet-lang.org#12]
If a .janet script file ends with a #comment and that comment does not have a linefeed character at the end, then the script may run as planned, but at the end this message comes:
```
parse error in XYZ.janet around byte NNN: unmatched delimiter
```

**Comment by bakpakin** [comment]
Thanks for the issue. For language bugs, please put them in the [Janet](https://github.com/janet-lang/janet) repo instead.

This was a parser issue, fixed in 3014a59c3e7f3c8d0c3707852173841eaf78c759
