### ISSUE TITLE
Link to Joy 404s

### ISSUE THREAD

**Issue by elimisteve** [janet-lang/janet-lang.org#137]
At https://janet-lang.org/ , the link to "Joy Web Framework" leads to joyframework.com , which returns a 404.

**Comment by elimisteve** [comment]
@oakmac Yup, that's what my PR does, and what @swlkr says is correct: https://github.com/janet-lang/janet-lang.org/pull/138

**Comment by sogaiu** [comment]
@elimisteve Since #138 was merged (the link on the site now works for me too), may be this issue can be closed?

**Comment by elimisteve** [comment]
@sogaiu Yes indeed!
