### ISSUE TITLE
Move "The Event Loop" before "Multithreading" in table of contents

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet-lang.org#144]
@pepe suggested [moving "The Event Loop" to a position before "Multithreading" in the table of contents](https://github.com/janet-lang/janet-lang.org/pull/143#issuecomment-946589242).  That seems like a more logical order to me too.

Unless there are objections, we can work on a PR toward this end once some decisions (merge / no-merge) are made about these related PRs: #141 and #143

IIUC, to change the order, one might change the numbers appropriately in the following lines:

* https://github.com/janet-lang/janet-lang.org/blob/master/content/docs/networking.mdz#L3
* https://github.com/janet-lang/janet-lang.org/blob/master/content/docs/threads.mdz#L3
* https://github.com/janet-lang/janet-lang.org/blob/master/content/docs/event_loop.mdz#L3

**Comment by sogaiu** [comment]
Looks like #141 and #143 have been merged.

@pepe (and any one else interested) The numbering is currently:

* [19](https://github.com/janet-lang/janet-lang.org/blob/2ef990154c299102aa0a910e0d7ffe3ff4a4d7f0/content/docs/threads.mdz#L3) - multithreading
* [20](https://github.com/janet-lang/janet-lang.org/blob/2ef990154c299102aa0a910e0d7ffe3ff4a4d7f0/content/docs/networking.mdz#L3) - networking
* [21](https://github.com/janet-lang/janet-lang.org/blob/2ef990154c299102aa0a910e0d7ffe3ff4a4d7f0/content/docs/event_loop.mdz#L3) - event loop

I guess the idea was to change this to:

* 19 - event loop
* 20 - multithreading
* 21 - networking

How does that seem?

**Comment by pepe** [comment]
Yep that seems reasonable to me.

**Comment by sogaiu** [comment]
Thanks.
