### ISSUE TITLE
No function to convert double -> binary representation

### ISSUE THREAD

**Issue by Techcable** [janet-lang/janet-lang.org#158]
Hi! I was writing trying to write a [msgpack](https://msgpack.org) implementation in pure Janet and I noticed there is no function to convert `double` -> bytes.

This is useful not just for serialization, but also for various bit hacks like estimating log2 or sqrt.

With the addition if `int/to-bytes` maybe you should consider adding `math/double-to-bytes`?

**Comment by bakpakin** [comment]
This is being addressed in the new ffi module with `(ffi/write :double x result-buffer)`, and corresponding `(ffi/read :double from-buffer)`.

**Comment by Techcable** [comment]
> This is being addressed in the new ffi module with  [...]

Glad to hear this :)

Unfortunately I opened this issue on the wrong place 🤦 

Could you maybe move it to the main repo?

**Comment by Techcable** [comment]
This issue belonged on the Janet main repo (my mistake).

I am closing it because it is solved by the addition of `ffi/write`
