### ISSUE TITLE
Auto-focusing search means you can't link to specific API functions

### ISSUE THREAD

**Issue by ianthehenry** [janet-lang/janet-lang.org#170]
If I follow a link like this:

https://janet-lang.org/api/index.html#map

I would expect it to take me directly to the `map` function. And in fact it does exactly that -- but if your browser executes JavaScript, the little search widget thing will scroll the page all the way up to the top a moment later.

**Comment by sogaiu** [comment]
> but if your browser executes JavaScript, the little search widget thing will scroll the page all the way up to the top a moment later.

It took me a bit to reproduce this.

I saw it happen in Firefox and Chromium but not Brave.

Also with [Dark Reader](https://darkreader.org/) enabled, initially I wasn't experiencing it.

Sometimes opening a second tab and then pasting the URL in and pressing Enter seemed to trigger it even with Dark Reader enabled (with both Firefox and Chromium).

Results didn't seem consistent.  A timing-related thing perhaps?

In any case, not nice.
