### ISSUE TITLE
PEG specials `true` and `false` lack docs on PEG page

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/janet-lang.org#189]
Now that https://github.com/janet-lang/janet/pull/1187 has been merged, may be it makes sense to add some docs for `true` and `false` as PEG specials.

Perhaps in [this section](https://janet-lang.org/docs/peg.html#Primitive-patterns)?

**Comment by pepe** [comment]
I would say go ahead with PR, dear friend. There is hardly anyone more proficient in this area, save bp 😊

**Comment by sogaiu** [comment]
I was thinking @CosmicToast might be particularly good (^^;

I didn't feel I understood well enough to articulate an appropriate description.
