### ISSUE TITLE
Document spork/utf8.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet-lang.org#206]
It's available, but it's not documented on janet website.

Plus, janet REPL doesn't provide autocompletion for janet modules...

It took some time to discover this module...

**Comment by sogaiu** [comment]
I didn't find a page for `spork/utf8` either.

Snooping around, it looks like there are a couple relevant-looking things that are from `spork/utf8` though:

* [spork/utf8/decode-rune](https://janet-lang.org/api/spork/index.html#spork/utf8/decode-rune)
* [spork/uft8/encode-rune](https://janet-lang.org/api/spork/index.html#spork/utf8/encode-rune)

But it seems there may not be a page specifically for `spork/utf8` (as compared with say, [one for `spork/argparse`](https://janet-lang.org/api/spork/argparse.html)).

Perhaps an appropriate file can get added to [this directory](https://github.com/janet-lang/janet-lang.org/tree/master/content/api/spork) and when the site is rebuilt things will work out?

Based on what I [see for `crc`](https://github.com/janet-lang/janet-lang.org/blob/905080ac178faed694282ccd5951fbc845824ef3/content/api/spork/crc.mdz), may be something like the following in a file named `utf8.mdz`?

```
(import ../gen-docs :as gen-docs)
(import spork/utf8 :export true)
(setdyn :source-linker (partial gen-docs/github-source-linker "janet-lang/spork" gen-docs/spork-version))

{:title "UTF8"
 :nav-title "utf8"
 :template "docpage.html"}
---

## Index

@gen-docs/gen-prefix-current[utf8/]
```

Don't really know how this works (^^;

**Comment by sogaiu** [comment]
Ok, I tried out the guessed steps above and it seems to work.

Created a related PR #211.

**Comment by amano-kenji** [comment]
:feet:

**Comment by sogaiu** [comment]
It looks like #211 has been merged, so may be this can be closed now.
