### ISSUE TITLE
Document `init.janet` for `import`.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet-lang.org#207]
```
> (import ./ok)
error: could not find module ./ok:
    ok.jimage
    ok.janet
    ok/init.janet
    ok.so
  in require-1 [boot.janet] on line 3025, column 20
  in import* [boot.janet] on line 3064, column 15
  in _thunk [repl] (tailcall) on line 2, column 1
```
In the above error, I saw that `(import ./ok)` tries to load `ok/init.janet` after trying to load `ok.janet`.

This behavior is not documented on https://janet-lang.org/docs/modules.html.

This is significant for module organization.

**Comment by sogaiu** [comment]
Although there is mention of `init.janet` at https://janet-lang.org/docs/modules.html, reading the text there didn't lead me to deduce the current behavior.

For reference, I think a relevant line of source in `boot.janet` is [this one](https://github.com/janet-lang/janet/blob/23b0fe9f8e9bcc391fe94b18db379c73f1e2c8a2/src/boot/boot.janet#L2808):

```janet
(module/add-paths "/init.janet" :source)
```

May be [this section of the website docs](https://janet-lang.org/docs/modules.html#Importing-a-module) would be a good place to mention behavior with respect to `init.janet`.

**Comment by sogaiu** [comment]
@amano-kenji #234, which was an attempt to address this issue was merged.

If you think this issue has been addressed, please close this issue.
