### ISSUE TITLE
Document `declare-bin`.

### ISSUE THREAD

**Issue by amano-kenji** [janet-lang/janet-lang.org#209]
I noticed that https://janet-lang.org/docs/jpm.html doesn't mention `declare-bin`.

**Comment by sogaiu** [comment]
This looks similar to https://github.com/janet-lang/janet-lang.org/issues/34.

**Comment by sogaiu** [comment]
There is now a PR (#212) with a proposal for an additional section that includes some documentation for some `declare-` callables, including `declare-bin`.

**Comment by amano-kenji** [comment]
:cat2:

**Comment by sogaiu** [comment]
As #212 has been merged, I think this can be closed now.
