### ISSUE TITLE
I think the docs for with might be worng...

### ISSUE THREAD

**Issue by eko234** [janet-lang/janet-lang.org#231]
Sorry if I'm too lazy to check it, but the docs currently say that `with` releases the resource on fail, I don't know if thats true, but for me it makes sense to release it either way... maybe the docs are not clear enough there... :p

**Comment by sogaiu** [comment]
At the time of this writing, `with`, `defer`, and `with-syms` are defined like this:

[with](https://github.com/janet-lang/janet/blob/384ee4f6a910248eb8576e2694e5aaf3293144b3/src/boot/boot.janet#L414-L422):

```janet
(defmacro with
  ``Evaluate `body` with some resource, which will be automatically cleaned up
  if there is an error in `body`. `binding` is bound to the expression `ctor`, and
  `dtor` is a function or callable that is passed the binding. If no destructor
  (`dtor`) is given, will call :close on the resource.``
  [[binding ctor dtor] & body]
  ~(do
     (def ,binding ,ctor)
     ,(apply defer [(or dtor :close) binding] body)))
```

[defer](https://github.com/janet-lang/janet/blob/384ee4f6a910248eb8576e2694e5aaf3293144b3/src/boot/boot.janet#L356-L367):

```janet
(defmacro defer
  ``Run `form` unconditionally after `body`, even if the body throws an error.
  Will also run `form` if a user signal 0-4 is received.``
  [form & body]
  (with-syms [f r]
    ~(do
       (def ,f (,fiber/new (fn :defer [] ,;body) :ti))
       (def ,r (,resume ,f))
       ,form
       (if (= (,fiber/status ,f) :dead)
         ,r
         (,propagate ,r ,f)))))
```

[with-syms](https://github.com/janet-lang/janet/blob/384ee4f6a910248eb8576e2694e5aaf3293144b3/src/boot/boot.janet#L345-L354):
```janet
(defmacro with-syms
  "Evaluates `body` with each symbol in `syms` bound to a generated, unique symbol."
  [syms & body]
  (var i 0)
  (def len (length syms))
  (def accum @[])
  (while (< i len)
    (array/push accum (in syms i) [gensym])
    (++ i))
  ~(let (,;accum) ,;body))
```

May be those bits help make it clearer?  Though I suppose without actual testing...

---

IIUC, it's sometimes the case that what is mentioned in docs [1] are the only parts that are intended (and as such, possibly no "guarantee" is implied for things left unsaid).  Perhaps not here though (^^;

---

[1] I presume the docs being referred to here are [these](https://janet-lang.org/api/index.html#with).  It's true that appears on janet-lang.org, but [the source for it is over at the janet repository](https://github.com/janet-lang/janet/blob/384ee4f6a910248eb8576e2694e5aaf3293144b3/src/boot/boot.janet#L414-L422) so if there are suggestions about changes, it might make more sense to mention them there...

**Comment by eko234** [comment]
Mmmm I see, I think we could at least reference defer or say the resource clean step will be done using defer, this way you can understand it without needing to go to the code

**Comment by sogaiu** [comment]
@eko234 While I agree that would be clearer, I'm not sure that "leaking" implementation details (in this case explicitly mentioning `defer`) into the docstring is such a good idea.

Still, may be the docstring could be improved along the lines you mentioned:

> it makes sense to release it either way

Perhaps something like:

```
    Evaluate `body` with some resource, which will be automatically 
    cleaned up even if there is an error in `body`.
```

If that sounds good, I can make a PR to the docstring over at the main repository.

**Comment by sogaiu** [comment]
/me only just now notices the irony in the title (^^;
