### ISSUE TITLE
Make URLs aesthetically pleasing

### ISSUE THREAD

**Issue by katomuso** [janet-lang/janet-lang.org#237]
Any chance of getting rid of the `.html` extension in every page URL and, more importantly, using kebab case instead of snake case?

For example, compare https://janet-lang.org/docs/data_structures/arrays.html to https://janet-lang.org/docs/data-structures/arrays. Doesn't the second one look much nicer?

**Comment by sogaiu** [comment]
One note on the general idea of changing the way current URLs are done...

If we value the ability of the links that folks have already "embedded" in various places (other web pages, bookmarks, etc.), having some way for the existing scheme to continue functioning might be worth considering.  Whether that's by having additional files, redirection, or some other means...

I'm not sure under what conditions it would be worth having that kind of extra arrangement.

Just my two local currency units :)
