### ISSUE TITLE
Documentation navigation links have weird styling in a narrow-enough window

### ISSUE THREAD

**Issue by roryokane** [janet-lang/janet-lang.org#7]
In a wide window, the navigation links are presented in a vertical list, which is fine:

![navigation links in wide window](https://user-images.githubusercontent.com/79168/52897654-f832ff00-31a4-11e9-9c84-f36f215b74b9.png)

But in a slightly narrower window (e.g. my browser window when my vertical tabs sidebar is showing), the navigation links are displayed horizontally in a row:

![navigation links in narrower window](https://user-images.githubusercontent.com/79168/52897660-06811b00-31a5-11e9-95c2-458f0eb96882.png)

This row display does not look good. It is weird that all of the links are close together except the last two, Syntax and Tables, which fill the whole row. Maybe the intent is to mimic tabs, but there are too many links for that.

As an alternative, first I suggest displaying a vertical list alongside the content, just like with a larger window. There still seems to be plenty of space for it. But for truly narrow windows, I suggest displaying a vertical list of links above the content, perhaps collapsed by default with some JavaScript to expand them.

**Comment by bakpakin** [comment]
This has been updated as the docs are now generated with [Mendoza](https://github.com/bakpakin/mendoza).
