### ISSUE TITLE
tweak code block colors for easier reading

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet-lang.org#76]
The code blocks in the Janet docs are intense, high contrast, and somewhat difficult to read. If you like the current color scheme, I suggest the following changes:

  * background: `#111` --> `#333`
  * .mdzsyn-symbol: `#9effff` --> `#afffff`
  * .mdzsyn-keyword: `#f92672` --> `#ff97bc`
  * .mdzsyn-coresym: `#fd971f` --> `#ffbc6d`

With those changes, please see these before and after pics:

<http://www.unexpected-vortices.com/temp/janet/janet-docs-code-blocks-before.png>

<http://www.unexpected-vortices.com/temp/janet/janet-docs-code-blocks-after.png>

If you'd rather not make those changes, perhaps a lower-contrast colorscheme?

**Comment by bakpakin** [comment]
Looks good to me, will merge. Thanks for the changes!

**Comment by uvtc** [comment]
Nice! You're welcome!

**Comment by uvtc** [comment]
Not sure of the protocol regarding who closes issues. The docs look great, so I'll close this. Thanks!
