### ISSUE TITLE
separate doc page just for top-level functions

### ISSUE THREAD

**Issue by uvtc** [janet-lang/janet-lang.org#77]
At <https://janet-lang.org/api/index.html>, all the functions (top-level functions (like map, filter, reduce, interpose, frequencies, etc.) and functions within modules (such as buffer/trim, os/getenv)) are all shown together on the same big page.

I think the api docs need an additional separate page that only shows the top-level functions (those not in any module).

I'm trying to learn the language and the built-in functions, but it's difficult to see just those core/top-level functions without being distracted by every function of every module.

**Comment by bakpakin** [comment]
Added: https://janet-lang.org/api/misc.html

**Comment by uvtc** [comment]
Awesome! Thank you, Calvin!
