### ISSUE TITLE
It is not clear which order to read documentation pages in

### ISSUE THREAD

**Issue by roryokane** [janet-lang/janet-lang.org#8]
The Documentation link on https://janet-lang.org/ links to the [Introduction](https://janet-lang.org/introduction.html) documentation page. However, on the navigation sidebar, this Introduction page is displayed in the middle of the other links, which are in alphabetical order:

![navigation links with Introduction selected](https://user-images.githubusercontent.com/79168/52897893-d38b5700-31a5-11e9-992a-45752f52ecc6.png)

It is not clear which page one should read next to get a good idea of the language. I have to read the whole list of links, then evaluate which link seems simplest among the pages I haven’t read yet.

I suggest implementing two solutions:

- Display the navigation links in order of suggested reading (most basic to most advanced). If some ordering is arbitrary, you could split the links into two sections: an “Introduction” section that is manually ordered and a “Reference” section that is alphabetically ordered.
- At the bottom of each page, display links to the next and previous pages. For example, on the “Introduction” page, display “Syntax &gt;” on the bottom-right corner and no link on the bottom-left corner.

**Comment by bakpakin** [comment]
I have reordered the documentation into a more linear format rather than an unordered collection of pages. There is also now a next link and previous link at the bottom and top of each document page.
