### ISSUE TITLE
Document jpm lockfile format

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet-lang.org#81]
I don't have jpm repository cache. I can't use `jpm make-lockfile`.

I want to manually write it.

**Comment by sogaiu** [comment]
Until there is documentation, here are a couple of concrete examples:

* https://github.com/andrewchambers/hermes/blob/862714467a8127be0c4b992f7b0100d61ca3668f/lockfile.jdn
* https://github.com/subsetpark/janet-cells/blob/a806f6675d7c28d19cdc814e32e6f13be2aa1f3b/lockfile.jdn

FWIW, it looks like some code that is involved in creating lockfiles is here: https://github.com/janet-lang/janet/blob/1837e89fe4628d79c0b388e6bf7f066b71758f8f/jpm#L869-L905

**Comment by sogaiu** [comment]
Looking at:

* https://github.com/janet-lang/janet/blob/1837e89fe4628d79c0b388e6bf7f066b71758f8f/jpm#L891
* https://github.com/janet-lang/janet/blob/1837e89fe4628d79c0b388e6bf7f066b71758f8f/jpm#L900-L905

it seems that one gets an array of structs where each struct has the keys `:repo` and `:sha`.  Perhaps the values corresponding to the keys are respectively, a url and an sha1 checkusm hash as strings.  The code seems to suggest that the structs are in some kind of order as well.

**Comment by andrewchambers** [comment]
A work around is to temporarily make one using jpm install into a temporary directory then copy the result.

**Comment by crocket** [comment]
I don't think lockfile is a substitute for proper versioning.
