### ISSUE TITLE
Document project.janet more thoroughly.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet-lang.org#82]
https://janet-lang.org/docs/jpm.html doesn't reflect what's possible now in project.janet.

For example, `:tag`.

**Comment by sogaiu** [comment]
Perhaps putting something appropriate in [this section](https://janet-lang.org/docs/jpm.html#Declaring-a-project) could improve things a bit.

**Comment by sogaiu** [comment]
I looked over a collection of `project.janet` files I had collected locally and found the following "top-level" keywords (filtered out some typos) used in `declare-project`:
```
:author
:authors
:dependencies
:desc
:description
:doc
:email
:jeep/dev-dependencies
:jeep/tree
:license
:name
:repo
:source
:url
:version
```
I think some of these are "unofficial" in the sense that AFAIU they don't have any current meaning (code-wise) from the perspective of jpm:
```
:authors
:desc
:doc
:email
:jeep/dev-dependencies
:jeep/tree
:source
```

FWIW `:tag` (mentioned in the OP), is not a "top-level" keyword so it didn't turn up during this investigation.

On a side note, there is a [`content` subdirectory at the jpm repository](https://github.com/janet-lang/jpm/tree/master/content) now.  Perhaps there is an intent to separate out jpm docs eventually.

**Comment by uvtc** [comment]
Thanks for investigating this, @sogaiu !

**Comment by sogaiu** [comment]
Regarding `:tag` and some others, currently, there is [the following code in jpm's `pm.janet`](https://github.com/janet-lang/jpm/blob/dacd2bbb8e35eee4502b1ed32d76412a213b5ff8/jpm/pm.janet#L112-L117):
```
  (if (dictionary? bundle)
    (do
      (set repo (or (get bundle :url) (get bundle :repo)))
      (set tag (or (get bundle :tag) (get bundle :sha) (get bundle :commit) (get bundle :ref)))
      (set btype (get bundle :type :git))
      (set shallow (get bundle :shallow false)))
```
As a list that includes:
* `:url`
* `:repo`
* `:tag`
* `:sha`
* `:commit`
* `:ref`
* `:type`
* `:shallow`

In the wild though, so far I've only noticed [`:tag` and `:repo`](https://github.com/saikyun/freja/blob/08555c4f4fef5c1942390c24d25c9b340605ed63/project.janet#L17).

**Comment by crocket** [comment]
Closing this for now.

**Comment by sogaiu** [comment]
I don't think that synonyms are being allowed but rather that people have made typos or were mistaken.  May be that's not correct though.

**Comment by crocket** [comment]
I'm in the process of retiring this github account. Create a new issue if you want.
