### ISSUE TITLE
Document dynamic variables.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet-lang.org#83]
`(dyn :args)` is not documented anywhere.
`(dyn :syspath)` is documented insufficiently in `man janet`.

I think important dynamic variables should be documented somewhere.

**Comment by sogaiu** [comment]
Some / more docs would be nice.

For reference, regarding `(dyn :args)`, here are some leads for examining related information:

* https://github.com/janet-lang/janet/commit/9118f2ce082d77529df2f35c2874e02296e8789b
* https://github.com/janet-lang/janet/commit/a0e98b9aa8556e42728a1ae970e16ea8e28729b5

For `:syspath`, the current janet man page has this bit:

>       -m syspath
>              Set the dynamic binding :syspath to the string syspath so that Janet will load
>              system modules from a directory different than the default. The default is set
>              when Janet is built, and defaults to /usr/local/lib/janet on Linux/Posix,  and
>              C:/Janet/Library on Windows. This option supersedes JANET_PATH.

and the jpm man page has a number of references.

Perhaps it's possible to look at those bits of text to come up with something?

On a side note, I've found that in some cases, there are useful bits that turn up via the gitter channel logs so it can be helpful to search there.

In any case, I agree that important dynamic variables being documented appropriately sounds good.

**Comment by harryvederci** [comment]
Addition: If it's possible to get a list of all current dynamic variables, could that be documented as well?

If not, maybe it would be nice if calling `(dyn)` without arguments could return a list of all current dynamic variables?

(= potential issue for the Janet repo, instead of this one)

**Comment by andrewchambers** [comment]
The current dynamic variables are all in the current env which you can query.

**Comment by sogaiu** [comment]
Perhaps [`all-dynamics`](https://janet-lang.org/api/index.html#all-dynamics) is useful for some of this?

```
$ janet
Janet 1.20.0-40ae2e81 linux/x64 - '(doc)' for help
repl:1:> (all-dynamics)
@[:args :doc-color :err-color :executable :peg-grammar :pretty-format :syspath]
repl:2:> (doc all-dynamics)


    function
    boot.janet on line 2823, column 1

    (all-dynamics &opt env local)

    Get all dynamic bindings in an environment. Defaults to the current 
    fiber's environment. If local is truthy, will not show inherited 
    bindings (from prototype tables).


nil
```

**Comment by crocket** [comment]
`all-dynamics` outputs a list of dynamic variables, but doesn't explain what they mean.

**Comment by sogaiu** [comment]
The specific items identified in the repl output above include:

* [:args](https://github.com/janet-lang/janet/blob/master/src/boot/boot.janet#L3578)
* [:doc-color](https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/CHANGELOG.md#1160---2021-05-30)
* [:err-color](https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/CHANGELOG.md#130---2019-09-05)
* [:executable](https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/CHANGELOG.md#120---2019-08-08)
* [:peg-grammar](https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/CHANGELOG.md#1142---2021-01-23)
* [:pretty-format](https://github.com/janet-lang/janet/blob/master/src/boot/boot.janet#L1661)
* [:syspath](https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/CHANGELOG.md#100---2019-07-01)

Links lead to hints about meaning.

**Comment by sogaiu** [comment]
Interestingly, that list does not quite match some of the output from `(doc)`:
```
:args :doc-color :err-color :executable :macro-lints :peg-grammar 
:pretty-format :syspath
```
Specifically, `:macro-lints` shows up via `(doc)`, but apparently not via `(all-dynamics)`.

**Comment by crocket** [comment]
Is it possible to document dynamic variables in source code? Emacs is good at documenting variables.

**Comment by bakpakin** [comment]
Dynamic bindings should indeed be better documented, but it is a bit difficult for auto generated docs since there is no way to tell which code is using a binding.

Guile has a nice wrapper around a similar mechanism that helps solve this problem: https://www.gnu.org/software/guile/manual/html_node/Parameters.html

**Comment by sogaiu** [comment]
With commit [461576e7](https://github.com/janet-lang/janet/commit/461576e7a29aefbef45ca31be2faca0f1c3632ef), there is now a mechanism for documenting dynamic variables in source.

Here is a list of things that make use of it:

* [\*defdyn-prefix\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1171-L1172)
* [\*out\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1173)
* [\*err\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1174)
* [\*macro-form\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1176-L1177)
* [\*current-file\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1179-L1180)
* [\*pretty-format\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1682-L1683)
* [\*macro-lints\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L1912-L1914)
* [\*err-color\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L2225-L2226)
* [\*doc-width\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L2864-L2865)
* [\*doc-color\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L2867-L2868)
* [\*args\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L3618-L3619)
* [\*executable\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L3621-L3623)
* [\*profilepath\*](https://github.com/janet-lang/janet/blob/a2ba0913d326e5eff067364b8b719a16d9d0ed9f/src/boot/boot.janet#L3625-L3626)

**Comment by crocket** [comment]
How can I see documentation for dynamic variables now?

**Comment by sogaiu** [comment]
@crocket Here's an example:
```
$ janet
Janet 1.21.2-a2ba0913 linux/x64 - '(doc)' for help
repl:1:> (doc *args*)


    keyword
    boot.janet on line 3618, column 1

    Dynamic bindings that will contain command line arguments at 
    program start


nil
```

**Comment by crocket** [comment]
What about the documentation for `syspath`?

**Comment by sogaiu** [comment]
As I mentioned [here](https://github.com/janet-lang/janet-lang.org/issues/83#issuecomment-1094901616) I don't see anything in `boot.janet` for it.

May be a PR to add something like the following would be accepted:
```
Path of directory to load system modules from.
```

**Comment by sogaiu** [comment]
@crocket https://github.com/janet-lang/janet/pull/949 has the suggested text and it was merged.

**Comment by sogaiu** [comment]
https://github.com/janet-lang/janet/commit/1aac0489d78a6771602c43d0a1344f94aa4c365a added `defdyn` forms for:
* `*redef*`
* `*debug*`
* `*exit*`
* `*exit-value*`
* `*lint-error*`
* `*lint-warn*`
* `*lint-levels*`
* `*peg-grammar*`

I think that covers everything I noticed.

@crocket How does it seem to you?

**Comment by crocket** [comment]
Looks good.

**Comment by sogaiu** [comment]
@crocket At least everything I noticed in `boot.janet` including what I see via `(all-dynamics)` appears to have been covered -- I believe that includes all items mentioned in this issue.

I don't know if there are any others.

**Comment by sogaiu** [comment]
@crocket May be if someone discovers some specific dynamic variables that have not been documented, separate issues / PRs can be made for those and in the mean time this issue can be closed.

What do you think?

**Comment by crocket** [comment]
Okay, I'm closing it.
