### ISSUE TITLE
Document main function.

### ISSUE THREAD

**Issue by crocket** [janet-lang/janet-lang.org#87]
It doesn't seem to be documented anywhere.

**Comment by sogaiu** [comment]
It looks to me like it can be triggered in a couple of places within `cli-main` in `boot.janet`:

* https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/src/boot/boot.janet#L3691
* https://github.com/janet-lang/janet/blob/40ae2e812ff5e186ba578d441de9f3d2bebd93fb/src/boot/boot.janet#L3704

`run-main` is currently defined earlier in `boot.janet` as:
```
(defn- run-main
  [env subargs arg]
  (if-let [entry (in env 'main)
           main (or (get entry :value) (in (get entry :ref) 0))]
    (let [thunk (compile [main ;subargs] env arg)]
      (if (function? thunk) (thunk) (error (thunk :error))))))
```
